# Generated by Django 4.2.10 on 2024-09-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_blogdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
