# Generated by Django 4.2.10 on 2024-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_delete_blogdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/top')),
                ('descount', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('listDes1', models.CharField(max_length=100)),
                ('listDes2', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
